# Generated by Django 5.1.4 on 2025-02-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerPrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('moisture', models.FloatField(default=0.0)),
                ('predicted_fertilizer', models.CharField(default='Unknown', max_length=50)),
            ],
            options={
                'db_table': 'fertilizer_predictions',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('moisture_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
