# Generated by Django 5.1.4 on 2025-02-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugas_akhir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizerprediction',
            old_name='humidity',
            new_name='Humidity',
        ),
        migrations.RenameField(
            model_name='fertilizerprediction',
            old_name='moisture',
            new_name='Moisture',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='moisture_level',
            new_name='Moisture',
        ),
    ]
