# Generated by Django 5.1.4 on 2025-03-10 14:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas_akhir', '0002_rename_humidity_fertilizerprediction_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizerprediction',
            name='Humidity',
        ),
        migrations.RemoveField(
            model_name='fertilizerprediction',
            name='Moisture',
        ),
        migrations.RemoveField(
            model_name='fertilizerprediction',
            name='Temperature',
        ),
        migrations.AddField(
            model_name='fertilizerprediction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fertilizerprediction',
            name='sensor_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_prediction', to='tugas_akhir.sensordata'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='crop_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='nitrogen',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='phosphorous',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='potassium',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='soil_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizerprediction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
