# Generated by Django 5.1.4 on 2025-03-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugas_akhir', '0003_remove_fertilizerprediction_humidity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='Temperature',
            new_name='temperature',
        ),
    ]
