# Generated by Django 5.1.4 on 2025-03-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugas_akhir', '0004_rename_temperature_sensordata_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='Humidity',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='Moisture',
            new_name='moisture',
        ),
    ]
