# Generated by Django 5.1.4 on 2025-03-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugas_akhir', '0005_rename_humidity_sensordata_humidity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
