# Generated by Django 5.1.4 on 2025-03-11 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas_akhir', '0006_rename_created_at_sensordata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_warning', to='tugas_akhir.sensordata')),
            ],
            options={
                'db_table': 'fertilizer_warnings',
            },
        ),
    ]
