# Generated by Django 5.1.4 on 2025-04-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas_akhir', '0007_fertilizerwarning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='phosphorous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
